/*
 * dma.h
 * (C) Guo Fu
 */
#ifndef _DMA_H_
#define _DMA_H_

#include <datatype.h>

/*
 * 单位是以页记，后续根据需求动态分配DMA所需连续空间，不过是要在16M以下空间的
 * 如果低字节地址被占用，那么就需要虚拟内存先将低地址空间的东西先放在外存中
 */
#define TRADITION_DMA_SIZE_MIN 1

#define DMA_HOST_CHANNAL_ZERO_PAGE_REGISTER 0x87
#define DMA_HOST_CHANNAL_ONE_PAGE_REGISTER 0x83
#define DMA_HOST_CHANNAL_TWO_PAGE_REGISTER 0x81
#define DMA_HOST_CHANNAL_THREE_PAGE_REGISTER 0x82
#define DMA_SLAVE_CHANNAL_FIVE_PAGE_REGISTER 0x8b
#define DMA_SLAVE_CHANNAL_SIX_PAGE_REGISTER 0x89
#define DMA_SLAVE_CHANNAL_SERVEN_PAGE_REGISTER 0x8a

#define DMA_CHANNAL_ZERO_BASE_ADDRESS 0x00
#define DMA_CHANNAL_ONE_BASE_ADDRESS 0x02
#define DMA_CHANNAL_TWO_BASE_ADDRESS 0x04
#define DMA_CHANNAL_THREE_BASE_ADDRESS 0x06

#define DMA_CHANNAL_ZERO_COUNT 0x01
#define DMA_CHANNAL_ONE_COUNT 0x03
#define DMA_CHANNAL_TWO_COUNT 0x05
#define DMA_CHANNAL_THREE_COUNT 0x07

#define DMA_COMMAND_STATUS_REGISTER 0x08
#define DMA_REQUEST_REGISTER 0x09
#define DMA_MASK_REGISTER 0x0a
#define DMA_MODE_REGISTER 0x0b
#define DMA_CLEAR_FLIP_FLOP_REGISTER 0x0c
#define MASTER_DMA_CLEAR_REGISTER 0x0d
#define DMA_MULTI_SHIELD 0x0f
#define SLAVE_DMA_CLEAR_REGISTER 0xda

#define DMA_MODE_REQ 0x00
#define DMA_MODE_BYTE 0x01
#define DMA_MODE_BLK 0x02
#define DMA_MODE_CASCADE 0x03

void master_clear_trigger();

#endif
